server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DB_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 10 # in seconds
  refreshable-duration: 120 # in seconds